name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file path/to/your-template.yml \
            --stack-name your-stack-name \
            --parameter-overrides \
              VPC=vpc-033eaabce0ebd2d08 \
              PublicSubnet1=subnet-00259a4b63a67b70f \
              PublicSubnet2=subnet-0c26e231c9633aca5 \
            --capabilities CAPABILITY_NAMED_IAM


# This workflow does the following:
1. **Triggers on push to the main branch**.
2. **Checks out the code**.
3. **Configures AWS credentials** using secrets stored in your GitHub repository.
4. **Deploys the CloudFormation stack** using the AWS CLI.

# Make sure to replace `path/to/your-template.yml` with the actual path to your CloudFormation template file and `your-stack-name` with the desired name for your CloudFormation stack. Also, ensure your AWS credentials and other necessary secrets are added to your repository secrets.

# If you need further customization or have specific requirements, feel free to let me know![1](https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-with-github-actions)[2](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions)
